### ISSUE TITLE
too much memory comsumption?

### ISSUE THREAD

**Issue by daaaaande** [ISUgenomics/SequelQC#4]
Hi, i was trying to run SequelQC on a hifireads.bam file:
./SequelQC.sh -u ../../../example_data/sample.hifi_reads.bam

Running in NO_SCRAPS mode
./SequelQC.sh: xrealloc: Konnte nicht 18446744073579733632 Bytes reservieren.
is basically saying could not allocate enough RAM.
acording to my calculator this would mean it needs a lot of RAM? how can i fix this?
any help would be appreciated

Cheers

**Comment by aseetharam** [comment]
Hello @daaaaande:
HiFi reads would be CCS reads and SequelTools will only work with subreads and/or scrap files, unfortunately. 
PS: SequelTools supersedes SequelQC and is available here: https://github.com/ISUgenomics/SequelTools

Thanks,
